name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: update apt
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt-get install -y cmake pkg-config libomp-dev clang libasound2-dev libglfw3-dev libvulkan-dev libjpeg-dev libpugixml-dev libfreetype-dev zlib1g-dev libexiv2-dev libxml2-utils rsync glslang-tools cargo rustc libavcodec-dev libavformat-dev
    - name: make
      run: make -j20
